project:
  type: website
  output-dir: docs

website:
  title: "Anny D. Rodriguez, Ph.D., MPH"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Courses
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - flatly
      - custom.scss
    css: styles.css
    toc: true

editor: visual


